[build-system]
requires = ['setuptools>=42.0',"wheel"]
build-backend = "setuptools.biuld_meta"

[tool.pytest.ini_options]
testpaths = [
    "test"
]
[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true